//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro_DACSN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> Tinhtrang { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
