//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro_DACSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MaChitietHoaDon { get; set; }
        public int MaHoaDon { get; set; }
        public Nullable<int> MaDV { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual DICHVU DICHVU { get; set; }
    }
}
