//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaTro_DACSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienNuoc
    {
        public System.DateTime NgayGhiDienNuoc { get; set; }
        public int MaPhong { get; set; }
        public int ChiSoDien { get; set; }
        public double GiaDien { get; set; }
        public int ChiSoNuoc { get; set; }
        public double GiaNuoc { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
